// Generated by self-service-suite-icons-generator. Do not edit by hand.
import type { SVGProps } from "react";

export function AppIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      width="1em"
      height="1em"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden="true"
      {...props}
    >
      <path d="M13,3V9H21V3M13,21H21V11H13M3,21H11V15H3M3,13H11V3H3V13Z" fill="currentColor" />
      <g fill="#cf0000"><rect x="11" y="15.95" width="12.6" height="2.7" /><rect x="15.95" y="11.5" width="2.7" height="12.6" /></g>
    </svg>
  );
}
